name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
        matrix:
          version: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            ${{ matrix.version }}/**
            .github/**
      - name: Set up QEMU
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: 'amd64,arm64'
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm:${{ matrix.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm:${{ matrix.version }}-${{ env.DOCKER_IMAGE_VERSION }}
      - name: Notify container release
        if: github.ref == 'refs/heads/main' && steps.changed-files.outputs.any_changed == 'true'
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ secrets.ZAPIER_WEBHOOK }}'
          method: 'POST'
          data: '{"message": "🐳📦🐘 Imagen ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm:${{ matrix.version }}-${{ env.DOCKER_IMAGE_VERSION }} disponible en Docker Hub."}'