name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
        matrix:
          version: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Echo php version
        run: |
          echo ${{ matrix.version }}
