name: Docker Image CI

#env:
#  PHP_VERSIONS: []

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-matrix:
    strategy:
        matrix:
          version: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: |
          ${{ matrix.version }}/**
          .github/**
    - name: generate array
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        echo "x=${{ matrix.version }}" >> $GITHUB_OUTPUT
  build:
    needs: [generate-matrix]
    strategy:
        matrix:
          version: "${{ needs.generate-matrix.outputs.x }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo php version
        run: |
          echo ${{ matrix.version }}
